import test from 'node:test';import assert from 'node:assert/strict';
import {createResearcher,acceptExtraction} from './pipeline.js';import {mockProvider,demoInput} from './providers.js';import {cloudProfiles} from './cloud-profiles.js';import {buildWebServer} from './research-app.mjs';import {affiliationQuote} from './identity.js';
test('recognizes school aliases without equating different schools',()=>{assert.equal(affiliationQuote('CS at UC Berkeley','University of California, Berkeley'),'UC Berkeley');assert.equal(affiliationQuote('UCLA','UC Berkeley'),'');});
test('indexed evidence remains literal and duplicate paraphrases collapse',()=>{const text='Maya Patel studies at Example University. Interested in social impact/non- ...';const result=acceptExtraction({identity:[{sourceId:'i',matches:true,nameEvidence:'Maya Patel',affiliationEvidence:'Example University'}],facts:[{sourceId:'i',claim:'She works in nonprofits',evidence:text},{sourceId:'i',claim:'Another invention',evidence:text}]},[{id:'i',text,kind:'search_index'}],demoInput);assert.equal(result.facts.length,1);assert.equal(result.facts[0].claim,'Search excerpt: '+text);});
test('unreadable selected page can produce explicitly limited indexed result',async()=>{const p=mockProvider();p.search=async()=>[{url:demoInput.profileUrl,title:'Maya Patel at Example University',description:'Maya Patel is a student at Example University studying robot navigation.'}];p.scrape=async()=>{throw Error('blocked')};p.extract=async(i,s)=>({identity:[{sourceId:s[0].id,matches:true,nameEvidence:'Maya Patel',affiliationEvidence:'Example University'}],facts:[{claim:'Robot navigation',sourceId:s[0].id,evidence:s[0].text}]});const r=await createResearcher(p)(demoInput);assert.equal(r.status,'ready');assert.equal(r.coverage,'indexed_only');assert.equal(r.identity.status,'indexed_match_not_verified');});
test('broader research is attempted and warnings survive partial failures',async()=>{let called=false;const p=mockProvider();p.searchBroader=async()=>{called=true;return []};await createResearcher(p)(demoInput);assert(called);});
test('cloud LinkedIn adapter needs no browser and only keeps professional fields',async()=>{let called;const p=cloudProfiles(mockProvider(),{SCRAPINGDOG_API_KEY:'fixture'},async url=>{called=url;return new Response(JSON.stringify([{fullName:'Maya Patel',public_identifier:'maya',education:[{school:'Example University'}],experience:[],email:'private@example.org',phone:'123',recommendations:'Unrelated person'}]));});const r=await p.scrape('https://www.linkedin.com/in/maya',new AbortController().signal);assert.equal(called.hostname,'api.scrapingdog.com');assert(!r.text.includes('private@'));assert(!r.text.includes('recommendations'));assert.equal(r.kind,'profile_provider');});
test('cloud adapter rejects mismatched provider identity',async()=>{const p=cloudProfiles(mockProvider(),{SCRAPINGDOG_API_KEY:'fixture'},async()=>new Response(JSON.stringify([{fullName:'Other',public_identifier:'other'}])));await assert.rejects(p.scrape('https://www.linkedin.com/in/maya',new AbortController().signal),/mismatched/);});
test('missing enrichment key is an explicit availability error',async()=>{await assert.rejects(cloudProfiles(mockProvider(),{}).scrape('https://www.linkedin.com/in/maya',new AbortController().signal),/not configured/);});
test('deployable server keeps secrets out of routes and limits API use',async()=>{const server=buildWebServer(async()=>({status:'ready'}),{origin:'http://127.0.0.1:8799',hourlyLimit:1});await new Promise(r=>server.listen(8799,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const headers={Host:'127.0.0.1:8799','Content-Type':'application/json'};try{assert.equal((await fetch(url+'/.env',{headers})).status,404);assert.equal((await fetch(url+'/api/research',{method:'POST',headers,body:'{}'})).status,200);assert.equal((await fetch(url+'/api/research',{method:'POST',headers,body:'{}'})).status,429);assert.equal((await fetch(url+'/api/research',{method:'POST',headers:{...headers,Origin:'https://untrusted.example'},body:'{}'})).status,403);}finally{await new Promise(r=>server.close(r));}});

test('distinct facts sharing a profile paragraph survive deduplication',()=>{const text='Maya Patel studies at Example University and built robots for Campus Club.';const raw={identity:[{sourceId:'s1',matches:true,evidence:text}],facts:[{sourceId:'s1',claim:'Studies at Example University',evidence:text},{sourceId:'s1',claim:'Built robots for Campus Club',evidence:text},{sourceId:'s1',claim:'Built robots for Campus Club',evidence:text}]};assert.equal(acceptExtraction(raw,[{id:'s1',text,kind:'profile_provider'}],demoInput).facts.length,2);});
test('readable web leads precede blocked social results and discovery remains visible',async()=>{const p=mockProvider();const attempted=[];p.search=async()=>Array.from({length:5},(_,i)=>({url:`https://www.instagram.com/p/${i}`,title:'Social'}));p.searchBroader=async()=>Array.from({length:9},(_,i)=>({url:`https://example.org/project-${i}`,title:'Project'}));const scrape=p.scrape;p.scrape=async(url,s)=>{attempted.push(url);return scrape(url,s)};const r=await createResearcher(p)(demoInput);assert.equal(attempted.length,10);assert(!attempted.some(u=>u.includes('instagram')));assert.equal(r.discovery.length,14);assert.equal(r.researchStats.attempted,10);});
test('profile-provider warnings are not mistaken for URL failures',async()=>{const p=mockProvider();const scrape=p.scrape;p.scrape=async(...args)=>({...await scrape(...args),kind:'profile_provider'});const r=await createResearcher(p)(demoInput);assert(r.warnings.some(w=>w.includes('masked')));assert(!r.warnings.some(w=>w.includes('unsuitable URL')));});

test('structured profile fields preserve truncation and cannot inherit model embellishment',()=>{const data={name:'Maya Patel',about:'Maya Patel studies at Example University in Business…',experience:[{company:'Campus Club',position:''}],education:[]};const text=JSON.stringify(data,null,2);const raw={identity:[{sourceId:'s1',matches:true,nameEvidence:'Maya Patel',affiliationEvidence:'Example University'}],facts:[{sourceId:'s1',claim:'Majors in Business Administration and Management',evidence:text}]};const r=acceptExtraction(raw,[{id:'s1',kind:'profile_provider',text}],demoInput);assert.equal(r.facts.length,2);assert(!r.facts.some(f=>f.claim.includes('Administration')));assert(r.facts.some(f=>f.claim.includes('Job title unavailable')));});
