// Keep writing and review aligned: personalization means a reason to connect,
// not reciting the viewer's resume before an unrelated question.
const contract = `Return six candidates, two of each kind: connection, advice, story. Put the stronger candidate first within each kind. The app selects the first valid candidate of each kind.
Each candidate has one spoken question, at most 35 words (prefer 15-27), valid subject factIds, and viewerEvidence copied exactly from an allowed excerpt. Connection and advice include I/my/I'm when viewer context exists. Without viewer context, do not invent it.
Read both complete profiles, work descriptions, interests, and timelines. Use past tense for completed roles. Facts belong to the person being met; viewerProfile belongs to the speaker. All premises must be supported. A title alone does not establish duties. Do not invent shared interests, motivations, lessons, challenges, achievements, recruiting experience, or a direct transition between nonadjacent roles. Do not turn ordinary degree progression into a career pivot.
One ask per candidate. No semicolons, stacked questions, resume lists, jargon, flattery, referral requests, private family questions, or demands for confidential work details. No 'how did you leverage', 'what would you focus on first', or 'what surprised you most'.`;

export const draftQuestionsPrompt = `Write openings for a relaxed first coffee chat, one notch more formal than talking to a friend. The goal is a relationship and an interesting exchange, not proving preparation or conducting an interview.
${contract}
Choose three different conversational threads:
- connection: the easiest genuine common ground. Shared campus, community, a documented interest, or an actual similar experience can be stronger than a prestigious employer. Briefly say what connects the viewer, then invite the person's own memory or perspective. A shared school is valid personalization; do not force a technical work comparison when a human connection is stronger.
- advice: one practical question relevant to the viewer's goal, grounded in something this person has actually experienced. When concrete viewer work descriptions exist, use ONE actual activity rather than merely repeating their industry goal. Ask about the subject's own experience with the related topic without assuming their duties. This should let the viewer compare experiences, not request a generic career plan, resume critique, or hypothetical consulting case. Do not make an early-career person speak for hiring managers or their whole firm.
- story: an inviting question about a different, specific part of their background. Select it using the viewer's interests or experience. A documented exchange location plus the viewer's interest in food can motivate a food recommendation WITHOUT claiming the subject is a foodie. A person's actual role can motivate asking what their work was like WITHOUT asserting their responsibilities. Never force travel or hobbies back into business lessons.
Keep the setup shorter than the question. Use ordinary words someone could comfortably say aloud. Let the person supply the interesting details instead of making up a sophisticated premise. A relevant simple question beats an elaborate forced connection. These are alternative threads, not a script to recite in sequence.`;

export const reviewQuestionsPrompt = `Edit these coffee-chat openings against both profiles. Rewrite weak candidates, then return six candidates with the strongest first in each kind.
${contract}
Audit in this order:
1. Truth: verify every first-person claim, subject premise, chronology, cited fact, and viewerEvidence. An activity does not prove a belief or lesson. Remove unsupported premises rather than soften them. Never attribute a firm's deals or strategy to this person.
2. Relationship: would this sound comfortable at a coffee table? Reject resume speeches, requests to evaluate the viewer's credentials, and corporate interview language. Prefer real common ground over employer name-dropping. Do not reject a shared-campus question merely because other alumni could ask it.
3. Answerability: can this particular person answer from their own life? Ask for a memory, preference, example, or experience. Avoid asking a new analyst to explain recruiting policy or big-picture firm strategy. Do not presume that every job or degree was a deliberate pivot.
4. Connection: the viewer detail must explain why they would ask this question. If removing that detail leaves a disconnected question, rebuild the bridge. For story, interests may explain relevance without being recited, but must affect the actual ask: food should lead to food, not a generic exchange memory; hiking should lead to outdoors, not an unrelated academic experience. Never pretend the subject shares an undocumented hobby. The advice candidate must use a concrete viewer activity when one is available, not merely their goal. Do not list several activities.
5. Variety: the first connection, advice, and story candidates should open three distinct threads. Favor a warm common-ground opening, one useful career conversation, and one different human or earlier-experience story. No three versions of 'help me get into your industry'.
6. Spoken quality: use a brief setup and a single easy-to-answer ask. Prefer 15-27 words, never over 35. Do not force cleverness or technical depth. No scores, editor commentary, or fabricated responses in the output.
Calibration examples illustrate wording only; NEVER copy their facts into the output:
- Weak: 'I built dashboards. What skill mattered most in your first job?' The ask ignores dashboards. Better if supported: 'I built dashboards during my internship. In your analyst role, how much time went into getting the data ready versus actually using it?'
- Weak: 'I love food. What did you learn working at a supermarket?' Food interest does not establish interest in supermarket operations. Better with a supported exchange location: 'I love trying new food. Was there a place you kept going back to during your exchange?'
- Weak: 'We went to the same school. How did campus shape your professional trajectory?' Better: 'I’m at your old university now. Is there anything you wish you’d made more time for while you were there?'
Prefer direct, concrete nouns in the ASK itself over 'skill', 'experience', 'perspective', or 'what stood out'. If the first candidate fails these examples' standard, rewrite it rather than leaving the better candidate second.`;
